Repository UnBArqDsw2022-2/2022.2_G4_IdotPet, pull requests merged in 2022-11, with the labels that each got.

#17 Doc/#2 politica organizacional
  docs/politicas/orgPolicies.md
Labels: documentation

#20 Doc/#11 tap
  docs/tap/tap.md
Labels: documentation

#22 Doc/#4 Documento 5W2H
  docs/_sidebar.md
  docs/base/5W2H.md
Labels: documentation

#18 Doc/#3 metodologia
  docs/produto/metodologia/metodologia.md
Labels: documentation

#30 Doc/#7 prototipos
  README.md
  docs/assets/prot_papel_ads/criar_conta.jpeg
  docs/assets/prot_papel_ads/detalhe_anuncio.jpeg
  docs/assets/prot_papel_ads/encontrar_ong.jpeg
  docs/assets/prot_papel_ads/favoritos.jpeg
  docs/assets/prot_papel_ads/login.jpeg
  docs/assets/prot_papel_ads/meus_anuncios.jpeg
  docs/sprints/sprint0/prototipoBaixaFidelidade.md
  docs/sprints/sprint0/wireframe.md
Labels: documentation

#32 Doc/#8 diagrama causa efeito
  docs/base/diagrama-causa-efeito.md
Labels: documentation

#37 Doc/#35 Corrigir revisores de documentos
  docs/base/5w2h.md
  docs/base/diagrama-causa-efeito.md
  docs/base/introspeccao.md
  docs/base/léxico.md
  docs/base/mapa_mental.md
  docs/base/rich_picture.md
Labels: documentation

#41 Pull Request do Doc/#7 modelagem bpmn
  docs/assets/bpmn/bpmn_diagrama.png
  docs/assets/bpmn/bpmn_diagrama_geral.png
  docs/assets/bpmn/bpmn_diagrama_produto.png
  docs/assets/bpmn/bpmn_diagrama_scrum.png
  docs/base/bpmn.md
  docs/base/metodologia.md
Labels: documentation

#45 Adicionando storyboard e documentação
  docs/assets/storyboard/storyboard_v1_0.jpeg
  docs/assets/storyboard/storyboard_v1_1.png
  docs/base/diagrama-causa-efeito.md
  docs/base/prototipoBaixaFidelidade.md
  docs/base/storyboard.md
Labels: documentation

#49 Doc/#44 tecnologias
  docs/base/tecnologias.md
Labels: documentation

#50 Doc/#9 lexico
  docs/base/5w2h.md
  docs/base/léxico.md
Labels: documentation

#71 #65 - Correção do BPMN com os verbos no infinitivo nos processos do diagrama
  docs/assets/bpmn/bpmn_diagrama.png
  docs/assets/bpmn/bpmn_diagrama_geral.png
  docs/assets/bpmn/bpmn_diagrama_produto.png
  docs/assets/bpmn/bpmn_diagrama_scrum.png
Labels: documentation, enhancement

#70 PR de docs/#54 - diagrama-de-classes
  docs/assets/diagrama_classe/diagrama_classe.png
  docs/modelagem/ddd.md
  docs/modelagem/diagrama_classe.md
Labels: documentation, Organization
